apiVersion: v1
kind: Service
metadata:
 name: db         # Name of the service
spec:
 selector:
    app: db                   # Selector to match the labels of the MySQL Pods
 ports:
    - protocol: TCP
      port: 3306               # Port MySQL is running on within the pod
      targetPort: 3306         # Port MySQL is listening on within the container

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: db
spec:
 replicas: 1
 selector:
    matchLabels:
      app: db
 template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
 name: web
spec:
 ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30002
 selector:
    app: web
 type: NodePort 

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: web
spec:
 replicas: 1
 selector:
    matchLabels:
      app: web
 template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 2; done;']
      containers:
        - name: web
          image: pavvanpradeep/cart-web
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_HOST
              value: db
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
 name: queue
spec:
 ports:
    - port: 8003
 selector:
    app: queue

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: queue
spec:
 replicas: 1
 selector:
    matchLabels:
      app: queue
 template:
    metadata:
      labels:
        app: queue
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 2; done;']
      containers:
        - name: queue
          image: pavvanpradeep/cart-queue
          command: ["python", "consumer.py"]
          imagePullPolicy: IfNotPresent
