version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8002'
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db

    environment:
      - DATABASE_HOST=localhost

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
