# Generated by Django 4.2.7 on 2024-04-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_cart_final_price_cart_user_id_cart_watch_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='final_price',
        ),
    ]
