# Generated by Django 4.2.7 on 2024-04-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_cart_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='watch_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(default=2),
        ),
    ]
