# Generated by Django 4.2.7 on 2024-04-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_cart_watch_id_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='brand',
            field=models.CharField(default='Default Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
