# Generated by Django 4.2.7 on 2024-04-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_cart_brand_cart_name_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
